version: 2
updates:
  # Scan NPM dependencies (Frontend)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  
  # Scan Python dependencies (Backend)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"